// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct connection (port 5432) for CLI operations (migrations, db push).
    // PgBouncer (port 6543) doesn't support DDL operations.
    url: process.env["DIRECT_URL"],
  },
});
